# Generated by Django 4.1.13 on 2023-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_customerbar_delete_mimodelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('yearsInCompany', models.IntegerField()),
            ],
        ),
    ]
